name: Publish PowerShell Script

on:
  workflow_dispatch:
  push:
    paths:
      - "version_v3.txt"
      - "IntuneAssignmentChecker_v3.ps1"
    branches:
      - main

jobs:
  publish-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read Version
        id: version
        shell: pwsh
        run: |
          $version = Get-Content version_v3.txt
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Create Temporary Script
        shell: pwsh
        run: |
          $content = Get-Content IntuneAssignmentChecker_v3.ps1
          $scriptContent = @"
          #Requires -Version 7.0
          #Requires -Modules Microsoft.Graph.Authentication

          <#PSScriptInfo
          .VERSION $env:VERSION
          .GUID c6e25ec6-5787-45ef-95af-8abeb8a17daf
          .AUTHOR ugurk
          .PROJECTURI https://github.com/ugurkocde/IntuneAssignmentChecker
          #>

          <#
          .DESCRIPTION
          This script enables IT administrators to efficiently analyze and audit Intune assignments. It checks assignments for specific users, groups, or devices, displays all policies and their assignments, identifies unassigned policies, detects empty groups in assignments, and searches for specific settings across policies.
          #>

          "@
          $scriptContent + ($content -join "`n") | Set-Content IntuneAssignmentChecker.ps1

      - name: Verify PowerShell Gallery Access
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          $ErrorActionPreference = 'Stop'
          try {
              # Register PSGallery if not already registered
              if (-not (Get-PSRepository -Name "PSGallery" -ErrorAction SilentlyContinue)) {
                  Register-PSRepository -Default -Verbose
              }
              
              # Set PSGallery as trusted
              Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted -Verbose
              
              # Test API key by getting package info
              $headers = @{
                  'X-NuGet-ApiKey' = $env:NUGET_API_KEY
              }
              $response = Invoke-WebRequest -Uri 'https://www.powershellgallery.com/api/v2/package' -Headers $headers -Method Head -UseBasicParsing -Verbose
              Write-Host "API Key validation successful"
          }
          catch {
              Write-Error "Failed to verify PowerShell Gallery access: $_"
              exit 1
          }

      - name: Publish to PowerShell Gallery
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          $ErrorActionPreference = 'Stop'
          try {
              # Publish the script with the original name
              Publish-Script -Path IntuneAssignmentChecker.ps1 -NuGetApiKey $env:NUGET_API_KEY -Verbose
          }
          catch {
              Write-Error "Failed to publish script: $_"
              exit 1
          }
